openapi: 3.0.3
info:
  title: Sedric Ai Speech Recognition - OpenAPI 3.0
  description: This is an assignment for Sedric Ai
  contact:
    email: bartosz.s.ziolo@gmail.com
  version: 0.0.1
servers:
  - url: 'https://yh19m3kdn9.execute-api.eu-west-3.amazonaws.com/'
tags:
  - name: speech-recognition
    description: Speech Recognition api
  - name: speech-recognition-audio
    description: Speech Recognition api file upload
paths:
  /recgonize:
    post:
      tags:
        - speech-recognition
      summary: Based on the `mp3` or `wav` file and text supplied, queue a job to decide if supplied text is present in the audio
      description: Based on the `mp3` or `wav` file and text supplied, queue a job to decide if supplied text is present in the audio
      operationId: speechRecgonition
      requestBody:
        description: Based on the `mp3` or `wav` file and text supplied, queue a job to decide if supplied text is present in the audio
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpeechReconigtionRequest"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpeechRecognitionResponse"
        "405":
          description: Invalid input

  /audio_upload:
    post:
      tags:
        - speech-recognition-audio
      summary: Upload a file for speech recgonition
      description: Upload a file for speech recgonition
      operationId: speechRecgonitionAudioUpload
      requestBody:
        description: Upload a file for speech recgonition
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio_file:
                  type: string
                  format: binary
              required:
                - audio_file
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpeechRecognitionResponse"
        "405":
          description: Invalid input


components:
  schemas:
    SpeechReconigtionRequest:
      type: object
      properties:
        audio_url:
          type: string
          example: "url/for/file.wav"
        sentences:
          type: array
          items:
            type: string
            example: ["hi my name is joe", "can you hear me?"]
      required:
        - audio_url
        - sentences

    SpeechRecognitionResponseBody:
      type: object
      properties:
        request_id:
          type: string
          example: "generated_request_id"
        message:
          type: string
          example: "Your request was accepted successfully"
      required:
        - request_id
        - message

    SpeechRecognitionResponse:
      type: object
      properties:
        body:
          $ref: "#/components/schemas/SpeechRecognitionResponseBody"
      required:
        - body